### ISSUE TITLE
Python 3.13 wheels

### ISSUE THREAD

**Issue by rphlo** [Isotr0py/pillow-jpegxl-plugin#74]
Would be nice to build wheels for new python version 3.13.

**Comment by Isotr0py** [comment]
Unfortunately, refer to [macos-14-Readme.md](https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md#python), [Windows2022-Readme.md](https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md#python) and [Ubuntu2204-Readme.md](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md#python), the release CI runner hasn't installed python3.13 by default.

I will keep an eye there and update a new release. 👀

**Comment by jfolz** [comment]
@Isotr0py may I suggest, for your own sanity, to look into cibuildwheel? They handle packaging shenanigans for you, including builds against RC Python on all platforms, so you can publish wheels early. I simply [run rustup inside their container](https://github.com/jfolz/ducer/blob/df2bc4e842e720946db1887d3435a2336aa3300a/.github/workflows/build_wheels.yml#L63) and it works great.

Installing from source failed for me because `jpegxl-sys` requires `libjxl >= 0.11.0`. Unless you're on rolling release, you will have to build that from source as well to get a version that recent. Looking at the release workflow, this is also what `pillow-jpegxl-plugin` does. Adding the `vendored` feature to the dependency instead was easy and did the trick :)
You can also add `cmake` as a build dependency to pyproject.toml, which should reduce external dependencies users have to install manually to a C compiler and the Rust toolchain.

**Comment by Isotr0py** [comment]
@jfolz Thanks for suggestions! I will take a look at [pypa/cibuildwheel](https://github.com/pypa/cibuildwheel) to see if it can be used to simplify the CI release workflow! :)

BTW, only the linux wheel release requires building `libjxl` from source since it doesn't have available up-to-date distribution for  `quay.io/pypa/manylinux_2_28_x86_64:latest` image. For windows/linux build, we directly use a pre-built `libjxl` distribution from MSYS2/Homebrew instead, which could be much faster than linux CI.

The reason why we use `dynamic` linking manually instead of `vendored` is that `vendored` use static linking which causes a serious performance regression. Here is the benchmark result between `vendored` and `dynamic`:

<details>
<summary> Vendored </summary>

```text
$ python benchmarks/benchmarks_encode.py -i test/images/bench.png
Quality: 98

Effort 1
  plugin    [size: 258714, duration: 0.448]
  reference [size: 258716, duration: 0.157]

Effort 2
  plugin    [size: 258714, duration: 0.476]
  reference [size: 258716, duration: 0.166]

Effort 3
  plugin    [size: 240657, duration: 0.697]
  reference [size: 240659, duration: 0.174]

Effort 4
  plugin    [size: 242940, duration: 2.211]
  reference [size: 242942, duration: 0.366]

Effort 5
  plugin    [size: 342423, duration: 2.927]
  reference [size: 342425, duration: 0.403]

Effort 6
  plugin    [size: 341787, duration: 3.041]
  reference [size: 341789, duration: 0.461]

Effort 7
  plugin    [size: 340736, duration: 3.649]
  reference [size: 340738, duration: 0.501]

Effort 8
  plugin    [size: 349518, duration: 22.701]
  reference [size: 349520, duration: 2.531]

Effort 9
  plugin    [size: 352913, duration: 35.302]
  reference [size: 352914, duration: 3.919]
```
</details>

<details>
<summary> Dynamic </summary>

```text
$ python benchmarks/benchmarks_encode.py -i test/images/bench.png
Quality: 98

Effort 1
  plugin    [size: 258714, duration: 0.141]
  reference [size: 258716, duration: 0.144]

Effort 2
  plugin    [size: 258714, duration: 0.173]
  reference [size: 258716, duration: 0.146]

Effort 3
  plugin    [size: 240657, duration: 0.176]
  reference [size: 240659, duration: 0.184]

Effort 4
  plugin    [size: 242940, duration: 0.381]
  reference [size: 242942, duration: 0.391]

Effort 5
  plugin    [size: 342423, duration: 0.437]
  reference [size: 342425, duration: 0.470]

Effort 6
  plugin    [size: 341787, duration: 0.542]
  reference [size: 341789, duration: 0.517]

Effort 7
  plugin    [size: 340736, duration: 0.583]
  reference [size: 340738, duration: 0.570]

Effort 8
  plugin    [size: 349518, duration: 2.687]
  reference [size: 349520, duration: 2.728]

Effort 9
  plugin    [size: 352912, duration: 3.920]
  reference [size: 352914, duration: 3.978]
```
</details>

**Comment by jfolz** [comment]
@Isotr0py that's a regression alright... I'm looking forward to replacing my wonky self-built wheel with a proper one, then ^^
Having managed custom build workflows in the past, I second my recommendation for cibuildwheel. It has saved me a lot of time. Now I only have to worry about unnecessary breaking changes in GitHub Actions.

**Comment by Isotr0py** [comment]
v1.3.0 with cpython3.13 wheels has released: https://pypi.org/project/pillow-jxl-plugin/#files

musllinux wheels for `x86`, `x64`, `arm_v7` and `aarch64` are also available now. 
(manylinux only has `x86` and `x64` because there are some issues about `jpegxl-rs` vendored building)
